FROM ubuntu:20.04

LABEL name="chaehyeon.song" \
		email="chaehyeon@snu.ac.kr" \
		version="2.0"

ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /tmp

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		build-essential \
		cmake \
		git \
		wget \
		libgoogle-glog-dev\
		libgflags-dev\
		libatlas-base-dev\
		libeigen3-dev\
		libsuitesparse-dev\
		libopencv-dev\
		python3-dev\
		python3-pip \
		python3-opencv\
		locales \
	&& locale-gen en_US.UTF-8 \
	&& update-locale LANG=en_US.UTF-8 \
	&& rm -rf /var/lib/apt/lists/*

# Install Ceres Solver
RUN wget http://ceres-solver.org/ceres-solver-2.2.0.tar.gz \
	&& tar xf ceres-solver-2.2.0.tar.gz \
	&& mkdir ceres-build && cd ceres-build \
	&& cmake ../ceres-solver-2.2.0 -DCMAKE_BUILD_TYPE=Release \
	&& make -j$(nproc) \
	&& make install

# Install yaml-cpp
RUN git clone https://github.com/jbeder/yaml-cpp.git \
	&& cd yaml-cpp \
	&& mkdir build && cd build \
	&& cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .. \
	&& make -j$(nproc) \
	&& make install

# Clean up build artifacts
RUN rm -rf /tmp/*

#-----------------------------------------------------------

RUN pip3 install pyinstaller scipy matplotlib pyyaml




# WORKDIR /app
# COPY . .

# RUN rm -rf build && mkdir build && cd build \
#   && cmake .. \
#   && make -j$(nproc)

# # Run PyInstaller with static .so detection
# RUN pyinstaller \
#     --onefile \
#     --add-binary "build/pydiscocal.cpython-38-x86_64-linux-gnu.so:." \
#     src/python/run_mono.py

# RUN pyinstaller \
#     --onefile \
#     --add-binary "build/pydiscocal.cpython-38-x86_64-linux-gnu.so:." \
#     src/python//run_stereo.py
