services:
  builder:
    build:
      context: ..
      dockerfile: runfiles/dockerfile
    volumes:
      - ../runfiles:/output
    command:  >
      sh -c "
        cp -r /app/dist/. /output
      "