cameras:
  - img_dir: "../sample_data/imgs/"
    cal_intrinsic: false
    type: "circle"
    n_x: 2 
    n_y: 2
    radius: 0.075
    distance: 0.24
    detection_mode: ""
    n_d: 2
    fx: 496.293
    fy: 496.357
    cx: 717.485
    cy: 572.079
    skew: 0.41766
    d1: -0.00921607
    d2: 0.00222301
    d3: 0
    d4: 0

  - img_dir: "../sample_data/imgs/"
    cal_intrinsic: false
    type: "circle"
    n_x: 2
    n_y: 2
    radius: 0.075
    distance: 0.24
    detection_mode: ""
    n_d: 2
    fx: 496.293
    fy: 496.357
    cx: 717.485
    cy: 572.079
    skew: 0.41766
    d1: -0.00921607
    d2: 0.00222301
    d3: 0
    d4: 0

options:
  save_results_path : "./"
  visualize : false