cameras:
  - img_dir: "../sample_imgs/rgb12/left/"
    cal_intrinsic: false
    detection_mode: "rgb"
    n_d: 2
    fx : 495.967255
    fy : 496.068058
    cx : 717.491681
    cy : 572.145376
    skew: 0.391476
    d1: -0.009047
    d2: 0.002273
    d3: 0.0
    d4: 0.0

  - img_dir: "../sample_imgs/rgb12/right/"
    cal_intrinsic: false
    detection_mode: "rgb"
    n_d: 2
    fx : 491.734090
    fy : 492.018165
    cx : 725.932057
    cy : 569.422536
    skew: 0.590477
    d1: -0.008312
    d2: 0.002411
    d3: 0.0
    d4: 0.0

target:
  type: "circle"
  n_x: 4 
  n_y: 3

  # rgb
  radius: 0.035
  c_distance: 0.09

options:
  mode : 0
  max_scene: 0
  sigma: 0
  visualize : true #check detection results
  save_results : true #Final results are saved in the results/ folder
  fix_radius : true
  save_pose : false
  save_rpe : false 
  save_jacob : false